// <auto-generated />
using System;
using CogLog.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CogLog.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CogLog.Domain.BrainBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalContext")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TopicId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Variant")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("BrainBlocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalContext = "adjective",
                            Content = "having a rosy complexion of the face.",
                            DateAdded = new DateTime(2024, 11, 5, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rubicund",
                            Url = "",
                            Variant = 0
                        },
                        new
                        {
                            Id = 2,
                            AdditionalContext = "adjective",
                            Content = "having or showing great knowledge.",
                            DateAdded = new DateTime(2024, 11, 12, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Erudite",
                            Url = "",
                            Variant = 0
                        },
                        new
                        {
                            Id = 3,
                            AdditionalContext = "noun",
                            Content = "A rectangular stepped tower found in ancient Mesopotamia.",
                            DateAdded = new DateTime(2024, 11, 23, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ziggurat",
                            Url = "",
                            Variant = 0
                        });
                });

            modelBuilder.Entity("CogLog.Domain.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Logo = "💻",
                            Title = "Coding"
                        },
                        new
                        {
                            Id = 2,
                            Logo = "🇯🇵",
                            Title = "Japanese"
                        },
                        new
                        {
                            Id = 3,
                            Logo = "📖",
                            Title = "Words"
                        });
                });

            modelBuilder.Entity("CogLog.Domain.BrainBlock", b =>
                {
                    b.HasOne("CogLog.Domain.Topic", "Topic")
                        .WithMany("BrainBlocks")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("CogLog.Domain.Topic", b =>
                {
                    b.Navigation("BrainBlocks");
                });
#pragma warning restore 612, 618
        }
    }
}
