name: Build, Publish and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.MD'
    
permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    secrets: inherit