name: Build, Publish and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.MD'
    
permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    uses: ./.github/workflows/build-and-publish.yml
    secrets: inherit
  deploy-ui:
    uses: ./.github/workflows/deploy-ui.yml
    needs: build-and-publish
    secrets: inherit
  deploy-api:
    uses: ./.github/workflows/deploy-api.yml
    needs: build-and-publish
    secrets: inherit