name: Deploy UI to Azure

on:
  workflow_call: 

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-ui-app.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download UI Artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-ui-app
          github-token: ${{ secrets.GH_PAT }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_66B319163EED416B990B6EC67AF35CE0 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D769539700A543BC96FAAFE7453B379A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B2576A2DC9A5407FA42D2C98A23C42DF }}

      - name: Deploy UI to Azure
        id: deploy-ui-app
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'adamjnav-coglog'
          slot-name: 'Production'
          package: .
    