name: Deploy API to Azure

on:
  workflow_call:

jobs:
  deploy:
    runs-on: windows-latest
    environment:
      name: 'API_PRODUCTION'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-api-app
          github-token: ${{ secrets.GH_PAT }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CAE2F936E1D04DEFB8A6A4AC9B180539 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A8C44CBB1C7B44DFBAD1A8E16192B069 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EA46FF41B88E48B68870325648DC2806 }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'coglog-api'
          slot-name: 'Production'
          package: .
    