name: Ping Azure App
on:
  schedule:
    - cron: '0/15 * * * *'
jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Run curl command
        run: |
          curl https://adamjnav-coglog.azurewebsites.net/